---
stages:
- cloudformation_compile 
tst:
  image: "${TST_ECR_REPOSITORY}/pnl-ecs-task"
  stage: cloudformation_compile
  artifacts:
    paths:
    - aws-*
  script:
  - export TASK_IMAGE_VERSION=1.0.22
  - export INTERFACES="flow-voormelding"
  - export APP_FLOW_NAME=hoi
  - export CONTEXT=pnp
  - export STATUS=active
  - export TST_APP_BW_APPLICATION_JOB_FLOWLIMIT=150 
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_HOST=0.0.0.0
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_PORT=8080
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_MINIMUMQTPTHREADS=10
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_MAXIMUMQTPTHREADS=75
  - export V1_NRP_VOORMELDING_CONTEXT_PATH=/nrp-processvoormelding/processvoormelding/v1
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_BASEPATH=/nrp-processvoormelding/processvoormelding
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_SPEC=v1
  - export TASK_LOAD_BALANCER=true
  - "/aws-ecs-task-compile"
  environment:
    name: tst
  only:
  - tst
  tags:
  - tst-cloudformation
acc:
  image: "${ACC_ECR_REPOSITORY}/pnl-ecs-task"
  stage: cloudformation_compile
  artifacts:
    paths:
    - aws-*
  script:
  - export TASK_IMAGE_VERSION=1.0.22
  - export TASK_LOAD_BALANCER=true
  - export APP_FLOW_NAME=hoi
  - export SERVICE_AUTO_SCALING=true
  - export SERVICE_AUTO_SCALING_MIN_CAPACITY=2
  - export SERVICE_AUTO_SCALING_MAX_CAPACITY=4
  - export SERVICE_AUTO_SCALING_METRIC=CPU 
  # reduced cooldown periode to increase speed of scaling
  - export SERVICE_AUTO_SCALING_COOLDOWN=60 
  - export INTERFACES="flow-voormelding"
  - export CONTEXT=pnp
  - export STATUS=active
  - export ACC_APP_BW_APPLICATION_JOB_FLOWLIMIT=150
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_HOST=0.0.0.0
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_PORT=8080
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_MINIMUMQTPTHREADS=10
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_MAXIMUMQTPTHREADS=75
  - export V1_NRP_VOORMELDING_CONTEXT_PATH=/nrp-processvoormelding/processvoormelding/v1
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_BASEPATH=/nrp-processvoormelding/processvoormelding
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_SPEC=v1
  - "/aws-ecs-task-compile"
  environment:
    name: acc
  only:
  - master
  tags:
  - acc-cloudformation
  

prd:
  image: "${PRD_ECR_REPOSITORY}/pnl-ecs-task"
  stage: cloudformation_compile
  artifacts:
    paths:
    - aws-*
  script:
  - export TASK_IMAGE_VERSION=1.0.22
  - export TASK_LOAD_BALANCER=true
  - export APP_FLOW_NAME=hoi
  - export SERVICE_AUTO_SCALING=true
  - export SERVICE_AUTO_SCALING_MIN_CAPACITY=2
  - export SERVICE_AUTO_SCALING_MAX_CAPACITY=10
  - export SERVICE_AUTO_SCALING_METRIC=CPU  
  # reduced cooldown periode to increase speed of scaling
  - export SERVICE_AUTO_SCALING_COOLDOWN=60
  - export INTERFACES="flow-voormelding"
  - export CONTEXT=pnp
  - export STATUS=active
  - export PRD_APP_BW_APPLICATION_JOB_FLOWLIMIT=150
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_HOST=0.0.0.0
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_PORT=8080
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_MINIMUMQTPTHREADS=10
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_MAXIMUMQTPTHREADS=75
  - export V1_NRP_VOORMELDING_CONTEXT_PATH=/nrp-processvoormelding/processvoormelding/v1
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_BASEPATH=/nrp-processvoormelding/processvoormelding
  - export APP_ESB_PES_NRP_VOORMELDING_CONNECTIONS_HTTP_REQREP_PROCESSVOORMELDING_HTTP_SPEC=v1
  - "/aws-ecs-task-compile"
  environment:
    name: prd
  only:
  - tags
  tags:
  - prd-cloudformation  

